# Configuration for Development environment
development:
  PORT: 5000
  DEBUG: True
  DB:
    HOSTNAME: ${DEV_HOSTNAME}
    USERNAME: ${DEV_USERNAME}
    PASSWORD: ${DEV_PASSWORD}
    DATABASE: ${DEV_DATABASE}